definitions:
  ClientError:
    properties:
      error:
        allOf:
        - $ref: '#/definitions/ErrCode'
        example: SERVER_NOT_RESPONDING
    type: object
  ErrCode:
    enum:
    - USER_INVALID_DATA
    - USER_ALREADY_EXISTS
    - USER_NOT_FOUND
    - SERVER_INTERNAL_ERROR
    - SERVER_NOT_RESPONDING
    - AUTH_INVALID_TOKEN
    - AUTH_EXPIRED_TOKEN
    type: string
    x-enum-varnames:
    - ErrUserInvalidData
    - ErrUserAlreadyExists
    - ErrUserNotFound
    - ErrServerInternalError
    - ErrServerNotResponding
    - ErrAuthInvalidToken
    - ErrAuthExpiredToken
  HttpOutput:
    properties:
      data:
        additionalProperties: {}
        type: object
    type: object
  SignUpWithEmailPasswordInput:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: StrongPassword1234
        maxLength: 72
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
host: localhost:3000
info:
  contact:
    email: AliMoradi0Business@gmail.com
    name: Ali Moradi
  description: Toppira APIs Documents.
  title: Toppira APIs
  version: "1.0"
paths:
  /auth/sign-up-with-user-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: Sign Up Input
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/SignUpWithEmailPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/HttpOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ClientError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ClientError'
      summary: sign up with email and password
      tags:
      - Authentication
swagger: "2.0"
