definitions:
  github_com_Toppira-Official_backend_internal_shared_dto.HttpOutputDto:
    properties:
      data:
        additionalProperties: {}
        type: object
    type: object
  github_com_Toppira-Official_backend_internal_shared_errors.ClientError:
    properties:
      error:
        $ref: '#/definitions/github_com_Toppira-Official_backend_internal_shared_errors.ErrCode'
    type: object
  github_com_Toppira-Official_backend_internal_shared_errors.ErrCode:
    enum:
    - SERVER_INTERNAL_ERROR
    - SERVER_NOT_RESPONDING
    - USER_INVALID_DATA
    - USER_ALREADY_EXISTS
    - USER_NOT_FOUND
    type: string
    x-enum-varnames:
    - ErrServerInternalError
    - ErrServerNotResponding
    - ErrUserInvalidData
    - ErrUserAlreadyExists
    - ErrUserNotFound
  internal_modules_auth_handler.SignUpWithEmailPasswordInput:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
host: localhost:3000
info:
  contact:
    email: AliMoradi0Business@gmail.com
    name: Ali Moradi
  description: Toppira APIs Documents.
  title: Toppira APIs
  version: "1.0"
paths:
  /auth/sign-up-with-user-password:
    post:
      consumes:
      - application/json
      parameters:
      - description: Sign Up Input
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_modules_auth_handler.SignUpWithEmailPasswordInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Toppira-Official_backend_internal_shared_dto.HttpOutputDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_Toppira-Official_backend_internal_shared_errors.ClientError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_Toppira-Official_backend_internal_shared_errors.ClientError'
      summary: sign up with email and password
      tags:
      - Authentication
swagger: "2.0"
